config/routes.rb
MapsProjectAidin::Application.routes.draw do
  resources :places do
    resources :comments
  end

  root :to => 'home#index'
  get "home/index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :place
  attr_accessible :body, :commenter
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :address, :description, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode, :if=> :address_changed?

  has_many :comments, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @comment = @place.comments.create(params[:comment])
    redirect_to place_path(@place)
  end

  def destroy
    @place = Place.find(params[:place_id])
    @comment = @place.comments.find(params[:id])
    @comment.destroy
    redirect_to place_path(@place)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def index
    @places = Place.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy  #using AJAX request for the destroy button
    @place = Place.find(params[:id])
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_path }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/comments/_comment.html.haml
%p
  %b Commenter:
  = comment.commenter
%p
  %b Comment:
  = comment.body
%p
  = link_to "Delete comment", [comment.place,comment], :confirm => "Do you want to delete this comment?", :method=> :delete

app/views/comments/_form.html.haml
= form_for([@place, @place.comments.build], :remote => false) do |c|
  .field
    = c.label :commenter
    %br/
    = c.text_field :commenter
  .field
    = c.label :body
    %br/
    = c.text_area :body
  .actions
    = c.submit

app/views/home/index.html.haml
%h1 Welcome to the Thoughts on Tourist Attractions
= link_to "Places seen", places_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sharedworld
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
    = javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"
    = javascript_include_tag "jquery-rails.js"
    = csrf_meta_tags
  %body
    = yield

app/views/places/_form.html.haml
= form_for(@place) do |f|
  - if @place.errors.any?
    #error_explanation
      %h2
        = pluralize(@place.errors.count, "error")
        prohibited this place from being saved:
      %ul
        - @place.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :address
    %br/
    = f.text_field :address
  .field
    = f.label :latitude
    %br/
    = f.text_field :latitude
  .field
    = f.label :longitude
    %br/
    = f.text_field :longitude
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/places/_place.html.haml
%tr
  %td= place.address
  %td= place.description
  %td= link_to 'Show', place
  %td= link_to 'Edit', edit_place_path(place)
  %td= link_to 'Destroy', place_path(place), :method=> :delete, :class=>"delete", :remote => true

app/views/places/destroy.js.haml
\/* Use fading when removing a location */
$('#place_#{@place.id}').fadeOut();
\/* Replace the count of places */
$("#places_count").html("#{pluralize(Place.count, 'Place')}");

app/views/places/edit.html.haml
%h1 Editing place
= render 'form'
= link_to 'Show', @place
|
=link_to 'Back', places_path

app/views/places/index.html.haml
%h1 Listing places
%table
  %tr
    %th{:align => "left"} Address
    %th{:align => "left"} Description
    %th
    %th
    %th
  %COLGROUP
    %col{:width => "250"}/
    %col{:width => "400"}/
    %col{:width => "0*"}/
    %col{:width => "0*"}/
    %col{:width => "0*"}/

  = render :partial => @places, :locals => { :list => true }
%br

= link_to 'New Place', new_place_path

app/views/places/new.html.haml
%h1 New place
= render 'form'
= link_to 'Back', places_path

app/views/places/show.html.haml
%p#notice= notice
%p
  %b Address:
  = @place.address
%p
  %b Latitude:
  = @place.latitude
%p
  %b Longitude:
  = @place.longitude
%p
  %b Description:
  = @place.description
%p
  %b Map:
  %br/
  = image_tag "http://maps.googleapis.com/maps/api/streetview?size=200x200&location=#{@place.latitude}%2C#{@place.longitude}&heading=235&sensor=false"
%p
  %b Map:
  %br/
  = image_tag "http://maps.googleapis.com/maps/api/staticmap?markers=#{@place.latitude}%2C#{@place.longitude}&zoom=3&size=200x200&sensor=false"
%h2 Comments:
= render @place.comments
%h2 New Comment:
= render "comments/form"
%br/
= link_to 'Edit', edit_place_path(@place)
|
=link_to 'Back', places_path